"""drop tempcol-v4

Revision ID: 75d2a14438b0
Revises: 46c24d4356d9
Create Date: 2021-09-05 16:55:19.911968

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '75d2a14438b0'
down_revision = '46c24d4356d9'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'tempcol')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items',
                    sa.Column('tempcol', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
